src/Entity/Utilisateurs.php
<?php

namespace App\Entity;

use App\Repository\UtilisateursRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UtilisateursRepository::class)]
class Utilisateurs implements UserInterface,  PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    #[Assert\Email(message: "L'adresse email '{{ value }}' n'est pas valide.")]
    private ?string $courriel = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $motdepasse = null;

    #[ORM\ManyToOne(inversedBy: 'utilisateurs')]
    private ?Roles $role = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCourriel(): ?string
    {
        return $this->courriel;
    }

    public function setCourriel(string $courriel): static
    {
        $this->courriel = $courriel;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getMotdepasse(): ?string
    {
        return $this->motdepasse;
    }

    public function setMotdepasse(string $motdepasse): static
    {
        $this->motdepasse = $motdepasse;

        return $this;
    }

    public function getRole(): ?Roles
    {
        return $this->role;
    }

    public function setRole(?Roles $role): static
    {
        $this->role = $role;

        return $this;
    }
    public function getRoles(): array
    {
        
        return [$this->role->getnom()]; // Assuming getnom() returns the role name
    }

    public function eraseCredentials()
    {
        // This method can be left blank, as no sensitive information needs to be erased
    }

    public function getUserIdentifier(): string
    {
        return $this->courriel;
    }
    public function getPassword(): ?string
    {
        return $this->motdepasse; // Assuming $password is a property holding the password
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Translation\TranslatorInterface;
use App\Repository\UtilisateursRepository;
use App\Entity\Utilisateurs;
use App\Form\UserType;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Http\Authenticator\Passport\Credentials\PasswordCredentials;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class SecurityController extends AbstractController
{
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route(path: 'admin/logout', name: 'app_logout')]
    public function logout(): void
    {
        
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
    #[Route(path: '/users', name: 'app_users')]
    public function manageUsers(UserRepository $repo)
    {
        $users = $repo->findAll();
        
        return $this->render('security/users.html.twig', ['users' => $users]);

    }    
    #[Route(path: '/users/edit/{id}', name: 'app_users_edit')]
    public function editUser($id, UserRepository $repo, User $user, Request $request, UserPasswordHasherInterface $userPasswordHasher)
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            // Check if password has been changed
            
            $plainPassword = $form->get('password')->getData();
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $plainPassword
                )
            );
    
            $repo->save($user, true);
    
            return $this->redirectToRoute('app_users', ['status' => 'useredited']);
        }
    
        return $this->render('security/edit.html.twig', [
            'formView' => $form->createView(),
        ]);
    }
  



    #[Route('/users/create', name:'app_users_create')]
    public function create(Request $request, UserRepository $repo, UserPasswordHasherInterface $userPasswordHasher) : Response {
        //create form for customer
        $user = new User;   
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        //if form correctly submitted and check, save to DB and return to customers table
        if($form->isSubmitted() && $form->isValid()){
            $plainPassword = $form->get('password')->getData();
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $plainPassword
                )
            );
           $repo->save($user, true);
           return $this->redirectToRoute('app_users', ['status' => 'usercreated']);
        }

        //show view with form to create product
        return $this->render('security/create.html.twig', [
           'formView' => $form->createView(),
        ]);
        
    }   
    #[Route('users/delete/{id}', name:'app_users_delete')]
    
    public function delete(UserRepository $repo, $id): Response
    {
      
     //find statement to delete
    $user = $repo->find($id);
    if (!$user) {
        throw $this->createNotFoundException(
            'No user found for id '.$id
        );
    }
    $repo->remove($user,1);
    
    
    //return statement disabled
    $message = 'User deleted';
    return new Response($message);
        
    }       
}

templates/security/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{'Create User'|trans}}{% endblock %}

{% block body %}
{% include '_partials/navigation.html.twig' %}
<div class="container">
    <div class="row mt-3 header ">
        <div class="col-6 ">
            <h1><i class="fa-solid fa-gift"></i> {{'Create User'|trans}}</h1>
        </div>
        <div class="col-3">
            <div id="status"></div>
        </div>
        <div class="col-3">
        </div>
    </div>
    <div class="row mt-3">
        <div class="col back"><h3><a href="{{ path('app_users') }}"><i class="fa-solid fa-backward"></i></a></h3></div>
    </div>      
    <div class="row mt-3">
        <form action="#" method="post" autocomplete="off">
            {{form(formView)}}
        </form>


    </div>
</div>




{% endblock %}

templates/security/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{'Edit User'|trans}}{% endblock %}

{% block body %}
{% include '_partials/navigation.html.twig' %}
<div class="container">
    <div class="row mt-3 header ">
        <div class="col-6 ">
            <h1><i class="fa-solid fa-gift"></i> {{'Edit User'|trans}}</h1>
        </div>
        <div class="col-3">
            <div id="status"></div>
        </div>
        <div class="col-3">
        </div>
    </div>
    <div class="row mt-3">
        <div class="col back"><h3><a href="{{ path('app_users') }}"><i class="fa-solid fa-backward"></i></a></h3></div>
    </div>      
    <div class="row mt-3">
        <form action="#" method="post" autocomplete="off">
            {{form(formView)}}
        </form>


    </div>
</div>




{% endblock %}

templates/security/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SecurityController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/garage/src/Controller/SecurityController.php'|file_link(0) }}">src/Controller/SecurityController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/garage/templates/security/index.html.twig'|file_link(0) }}">templates/security/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Se connecter{% endblock %}

{% block body %}
<center>
<form method="post" class="text-center" id="login">
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {% if app.user %}
        <div class="mb-3">
            
        </div>
    {% endif %}
<center><img class="logo" src="images/logo.png" /></center>
<div style="display:inline-block;width:20rem;" class="card text-white bg-primary mb-3 text-center mt-5" style="max-width: 20rem;">

  <div class="card-body text-center">
    <!--<label for="inputEmail">Email</label>-->
    <input type="email" value="{{ last_username }}" name="email" id="inputEmail" placeholder="Email" class="form-control text-center" autocomplete="email" required autofocus>
    <!--<label for="inputPassword">{{'Password'|trans}}</label>-->
    <input type="password" name="password" id="inputPassword" class="form-control text-center" placeholder="Mot de passe" autocomplete="current-password" required>
    <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
    >
    <button class="btn btn-lg btn-secondary mt-4 text-center " type="submit">
        Se connecter
    </button>
  </div>
</div>

    {#
        Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
        See https://symfony.com/doc/current/security/remember_me.html

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" name="_remember_me"> Remember me
            </label>
        </div>
    #}


</form>
</center>
{% endblock %}

templates/security/users.html.twig
{% extends 'base.html.twig' %}
{% block title %} {{ 'Users'|trans }}{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="/includes/js/users.js"></script>
{% endblock %}
{% block body %}
{% include '_partials/navigation.html.twig' %}
<!-- End of action and title bar-->
<div class="container">
    <div class="row mt-3 header ">
        <div class="col-6 ">
            <h1>
                    <i class="fa fa-user"></i> {{ 'Users'|trans }}
            </h1>
        </div>
        <div class="col-3">
            <div id="status"></div>
        </div>
        <div class="col-3">
          
        </div>
    </div>
</div>
<div class="row mt-3">
    <div style="overflow-x:auto; width:100%">
        <div class="container customtable">
            <div class="row last">
                <div class="col"></div>
                <div class="col"></div>
                <div class="col"></div>
                <div class="col"></div>
                {% if app.request.get('_route') == 'app_products_disabled_show' %}
                <div class="col last"><h3><a href="{{ path('app_users') }}"><i class="fa-solid fa-backward"></i></a></h3></div>
                {% else %}
                <div class="col last"><h3><a href="{{ path('app_users_create') }}"><i class="fa fa-plus"></i></a></h3></div>
                {% endif %}
            </div>   
        </div>
    </div>
</div>
<div class="row mt-3">
    <div style="overflow-x:auto; width:100%">
        <div class="container customtable">
            <div class="row header">
                <div class="col">{{'Email' | trans}}</div>
                <div class="col">{{'Role' | trans}}</div>
                <div class="col">{{'Actions' | trans}}</div>
            </div>
            {% for user in users %} 
                <div class="row normal">
                    <div class="col email" >{{user.email}}</div>
                    <div class="col role" >
                        {% for role in user.roles %}
                            {{role}}
                        {% endfor %}
                    </div>
                    <div class="col actions" >&nbsp;<a href="users/edit/{{user.id}}"><i class="fa fa-pen-to-square"></i></a><a id="disable" href="#" onclick="deleteUser({{user.id}})"  ><i class="fa fa-trash"></i></a></div>
                </div>
            {% endfor %} 
        </div>
    </div>
</div>

</div>

</div>

{% endblock %}